from PyQt6 import QtCore, QtGui, QtWidgets

SIGLAESTADOS = ['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO']
UNIDADES = ['CM', 'CM2', 'CM3', 'CX', 'DZ', 'G', 'KG', 'L', 'M', 'M2', 'M3', 'ML', 'PAR', 'PCT', 'ROLO', 'UN']

class TelaCadastroOrcamento(QtWidgets.QMainWindow):

        def __init__(self):
                super(TelaCadastroOrcamento, self).__init__()
                self.setupUi()

        def setupUi(self):

                self.resize(1280, 760)
                self.main_frame = QtWidgets.QFrame(self)
                self.main_frame.setObjectName("main_frame")
                self.vlayout6 = QtWidgets.QVBoxLayout(self.main_frame)               
                #frame titulo
                self.frame_titulo = QtWidgets.QFrame(self.main_frame)
                self.vlayout6.addWidget(self.frame_titulo)
                self.labelTitulo = QtWidgets.QLabel(self.frame_titulo)
                self.labelTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
                self.labelTitulo.setObjectName("titulo")
                self.vlayout6.setContentsMargins(18, 18, 18, 18)
                self.vlayout6.setSpacing(36)
                self.vlayout6.addWidget(self.labelTitulo)
                self.framedados = QtWidgets.QFrame(self.main_frame)
                self.gridLayout = QtWidgets.QGridLayout(self.framedados)
                self.gridLayout.setVerticalSpacing(9)
                self.gridLayout.setHorizontalSpacing(9)
                self.vlayout6.addWidget(self.framedados)               
                #dados do cliente
                self.groupBoxCliente = QtWidgets.QGroupBox(self.framedados)
                self.gridLayoutCliente = QtWidgets.QGridLayout(self.groupBoxCliente)
                self.gridLayoutCliente.setVerticalSpacing(9)
                self.gridLayoutCliente.setHorizontalSpacing(9)
                self.botaobuscarcliente = QtWidgets.QPushButton(self.groupBoxCliente)
                self.botaobuscarcliente.setFixedSize(180,25)
                self.gridLayoutCliente.addWidget(self.botaobuscarcliente, 0, 0, 1, 2)
                self.checkboxNovoCliente = QtWidgets.QCheckBox(self.groupBoxCliente)
                self.checkboxNovoCliente.setChecked(True)
                self.gridLayoutCliente.addWidget(self.checkboxNovoCliente, 0, 2, 1, 2)
                self.labelPessoa = QtWidgets.QLabel(self.groupBoxCliente)
                self.gridLayoutCliente.addWidget(self.labelPessoa, 1, 0, 1, 1)
                self.comboBoxPessoa = QtWidgets.QComboBox(self.groupBoxCliente)
                self.comboBoxPessoa.addItems(["FÍSICA", "JURÍDICA"])
                self.gridLayoutCliente.addWidget(self.comboBoxPessoa, 1, 1, 1, 1)
                self.labelcpfj = QtWidgets.QLabel(self.groupBoxCliente)
                self.gridLayoutCliente.addWidget(self.labelcpfj, 1, 2, 1, 1)
                self.lineEditCPFJ = QtWidgets.QLineEdit(self.groupBoxCliente)
                self.gridLayoutCliente.addWidget(self.lineEditCPFJ, 1, 3, 1, 2)               
                self.labelNome = QtWidgets.QLabel(self.groupBoxCliente)
                self.gridLayoutCliente.addWidget(self.labelNome, 2, 0, 1, 1)
                self.lineEditNomeCliente = QtWidgets.QLineEdit(self.groupBoxCliente)
                self.gridLayoutCliente.addWidget(self.lineEditNomeCliente, 2, 1, 1, -1)
                self.labelCEP = QtWidgets.QLabel(self.groupBoxCliente)
                self.gridLayoutCliente.addWidget(self.labelCEP, 3, 0, 1, 1)
                self.lineEditCEP = QtWidgets.QLineEdit(self.groupBoxCliente)
                self.gridLayoutCliente.addWidget(self.lineEditCEP, 3, 1, 1, 1)
                self.labelEnder = QtWidgets.QLabel(self.groupBoxCliente)
                self.gridLayoutCliente.addWidget(self.labelEnder, 3, 2, 1, 1)
                self.lineEditEnder = QtWidgets.QLineEdit(self.groupBoxCliente)
                self.gridLayoutCliente.addWidget(self.lineEditEnder, 3, 3, 1, 2)
                self.labelNumero = QtWidgets.QLabel(self.groupBoxCliente)
                self.gridLayoutCliente.addWidget(self.labelNumero, 3, 5 ,1 ,1)
                self.lineEditNumero = QtWidgets.QLineEdit(self.groupBoxCliente)
                self.gridLayoutCliente.addWidget(self.lineEditNumero, 3, 6, 1, 1)
                self.labelBairro = QtWidgets.QLabel(self.groupBoxCliente)
                self.gridLayoutCliente.addWidget(self.labelBairro, 4, 0, 1, 1)
                self.lineEditBairro = QtWidgets.QLineEdit(self.groupBoxCliente)
                self.gridLayoutCliente.addWidget(self.lineEditBairro, 4, 1, 1, 2)
                self.labelCidade = QtWidgets.QLabel(self.groupBoxCliente)
                self.gridLayoutCliente.addWidget(self.labelCidade, 4, 3, 1, 1)
                self.lineEditCidade = QtWidgets.QLineEdit(self.groupBoxCliente)
                self.gridLayoutCliente.addWidget(self.lineEditCidade, 4, 4, 1, 1)
                self.labelUF = QtWidgets.QLabel(self.groupBoxCliente)
                self.gridLayoutCliente.addWidget(self.labelUF, 4, 5, 1, 1)
                self.comboBoxuf = QtWidgets.QComboBox(self.groupBoxCliente)
                self.comboBoxuf.addItems(SIGLAESTADOS)
                self.comboBoxuf.setCurrentIndex(15)
                self.gridLayoutCliente.addWidget(self.comboBoxuf, 4, 6, 1, 1)
                self.labelFone1 = QtWidgets.QLabel(self.groupBoxCliente)
                self.gridLayoutCliente.addWidget(self.labelFone1, 6, 0, 1, 1)            
                self.lineEditFone1 = QtWidgets.QLineEdit(self.groupBoxCliente)
                self.gridLayoutCliente.addWidget(self.lineEditFone1, 6, 1, 1, 2)            
                self.labelFone2 = QtWidgets.QLabel(self.groupBoxCliente)
                self.gridLayoutCliente.addWidget(self.labelFone2, 6, 3, 1, 1)
                self.lineEditFone2 = QtWidgets.QLineEdit(self.groupBoxCliente)
                self.gridLayoutCliente.addWidget(self.lineEditFone2, 6, 4, 1, 3)         
                self.gridLayoutCliente.setColumnStretch(1,0)
                self.gridLayoutCliente.setColumnStretch(4,4)
                self.gridLayoutCliente.setColumnStretch(6,2)

                self.gridLayout.addWidget(self.groupBoxCliente, 0, 0, 2, 1)
                #dados do veiculo
                self.groupBoxVeiculo = QtWidgets.QGroupBox(self.framedados)
                self.gridLayoutVeiculo = QtWidgets.QGridLayout(self.groupBoxVeiculo)
                self.botaobuscarveiculo = QtWidgets.QPushButton(self.groupBoxVeiculo)
                self.botaobuscarveiculo.setFixedSize(180,25)
                self.gridLayoutVeiculo.addWidget(self.botaobuscarveiculo, 0, 0, 1, 2)
                self.checkboxNovoVeiculo = QtWidgets.QCheckBox(self.groupBoxVeiculo)
                self.checkboxNovoVeiculo.setChecked(True)
                self.gridLayoutVeiculo.addWidget(self.checkboxNovoVeiculo, 0, 2, 1, 1)
                self.labelMarca = QtWidgets.QLabel(self.groupBoxVeiculo)
                self.gridLayoutVeiculo.addWidget(self.labelMarca, 1, 0, 1, 1)
                self.comboBoxMarca = QtWidgets.QComboBox(self.groupBoxVeiculo)
                self.comboBoxMarca.setEditable(True)
                self.gridLayoutVeiculo.addWidget(self.comboBoxMarca, 1, 1, 1, 3) 
                self.labelPlaca = QtWidgets.QLabel(self.groupBoxVeiculo)
                self.gridLayoutVeiculo.addWidget(self.labelPlaca, 1, 4, 1, 1)
                self.lineEditPlaca = QtWidgets.QLineEdit(self.groupBoxVeiculo)
                self.gridLayoutVeiculo.addWidget(self.lineEditPlaca, 1, 5, 1, 1)
                self.labelModelo = QtWidgets.QLabel(self.groupBoxVeiculo)
                self.gridLayoutVeiculo.addWidget(self.labelModelo, 2, 0, 1, 1)            
                self.lineEditModelo = QtWidgets.QLineEdit(self.groupBoxVeiculo)
                self.gridLayoutVeiculo.addWidget(self.lineEditModelo, 2, 1, 1, 3)          
                self.labelAno = QtWidgets.QLabel(self.groupBoxVeiculo)
                self.gridLayoutVeiculo.addWidget(self.labelAno, 2, 4, 1, 1)
                self.lineEditAno = QtWidgets.QLineEdit(self.groupBoxVeiculo)
                self.gridLayoutVeiculo.addWidget(self.lineEditAno, 2, 5, 1, 1)
                self.labelKm = QtWidgets.QLabel(self.groupBoxVeiculo)
                self.gridLayoutVeiculo.addWidget(self.labelKm, 3, 0, 1, 1)
                self.lineEditKm = QtWidgets.QLineEdit(self.groupBoxVeiculo)
                self.gridLayoutVeiculo.addWidget(self.lineEditKm, 3, 1, 1, 1)
                self.gridLayoutVeiculo.setColumnStretch(1,0)
                self.gridLayoutVeiculo.setColumnStretch(2,0)
                self.gridLayoutVeiculo.setColumnStretch(3,4)
                self.gridLayoutVeiculo.setColumnStretch(5,3)

                self.gridLayout.addWidget(self.groupBoxVeiculo, 0, 1, 1, 1)
                #dados especificos do orçamento
                self.groupBoxOrcamento = QtWidgets.QGroupBox(self.framedados)
                self.gridLayoutOrc = QtWidgets.QGridLayout(self.groupBoxOrcamento)
                self.labelData = QtWidgets.QLabel(self.groupBoxOrcamento)
                self.gridLayoutOrc.addWidget(self.labelData, 0, 0, 1, 1)
                self.lineEditData = QtWidgets.QDateEdit(self.groupBoxOrcamento)
                self.lineEditData.setCalendarPopup(True)
                self.lineEditData.setDateTime(QtCore.QDateTime.currentDateTime())
                self.gridLayoutOrc.addWidget(self.lineEditData, 0, 1, 1, 1)
                self.labelDataPrev = QtWidgets.QLabel(self.groupBoxOrcamento)
                self.gridLayoutOrc.addWidget(self.labelDataPrev, 0, 2, 1, 1)
                self.lineEditDataPrev = QtWidgets.QDateEdit(self.groupBoxOrcamento)
                self.lineEditDataPrev.setCalendarPopup(True)
                self.lineEditDataPrev.setDateTime(QtCore.QDateTime.currentDateTime())
                self.gridLayoutOrc.addWidget(self.lineEditDataPrev, 0, 3, 1, 1)
                self.gridLayout.addWidget(self.groupBoxOrcamento, 1, 1, 1, 1)
                #peças
                self.groupBoxPecas = QtWidgets.QGroupBox(self.framedados)
                self.vlayoutgpecas = QtWidgets.QVBoxLayout(self.groupBoxPecas)
                self.vlayoutgpecas.setContentsMargins(1, 1, 1, 1)
                self.scrollarea1 = QtWidgets.QScrollArea(self.groupBoxPecas)
                self.scrollarea1.setWidgetResizable(True)
                self.scrollarea1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
                self.vlayoutgpecas.addWidget(self.scrollarea1)
                self.framegroupboxpecas = QtWidgets.QFrame(self.scrollarea1)
                self.framegroupboxpecas.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
                self.scrollarea1.setWidget(self.framegroupboxpecas)
                self.gridLayout_2 = QtWidgets.QGridLayout(self.framegroupboxpecas)
                self.labelNomePeca = QtWidgets.QLabel(self.framegroupboxpecas)
                self.gridLayout_2.addWidget(self.labelNomePeca, 0, 0, 1, 1)
                self.lineEditNomePeca = QtWidgets.QLineEdit(self.framegroupboxpecas)
                self.gridLayout_2.addWidget(self.lineEditNomePeca, 0, 1, 1, 1)
                self.labelQtde = QtWidgets.QLabel(self.framegroupboxpecas)
                self.gridLayout_2.addWidget(self.labelQtde, 0, 2, 1, 1)
                self.lineEditQtdeP = QtWidgets.QLineEdit(self.framegroupboxpecas)      
                self.gridLayout_2.addWidget(self.lineEditQtdeP, 0, 3, 1, 1)
                self.labelUn = QtWidgets.QLabel(self.framegroupboxpecas)      
                self.gridLayout_2.addWidget(self.labelUn, 0, 4, 1, 1)
                self.comboBoxUn = QtWidgets.QComboBox(self.framegroupboxpecas)
                self.comboBoxUn.addItems(UNIDADES)
                self.comboBoxUn.setMinimumWidth(50)
                self.comboBoxUn.setCurrentIndex(15)
                self.gridLayout_2.addWidget(self.comboBoxUn, 0, 5, 1, 1)
                self.labelValorPeca = QtWidgets.QLabel(self.framegroupboxpecas)
                self.gridLayout_2.addWidget(self.labelValorPeca, 0, 6, 1, 1)
                self.lineEditValorPeca = QtWidgets.QLineEdit(self.framegroupboxpecas)
                self.gridLayout_2.addWidget(self.lineEditValorPeca, 0, 7, 1, 1)
                self.botaoAddPecas = QtWidgets.QPushButton(self.framegroupboxpecas, clicked=self.addLinhaPeca)
                self.gridLayout_2.addWidget(self.botaoAddPecas, 0, 8, 1, 1)           
                self.linhasPeca = [[self.lineEditNomePeca, self.lineEditQtdeP, self.comboBoxUn, self.lineEditValorPeca]]
                self.spacerpeca = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
                self.gridLayout_2.addItem(self.spacerpeca, 1, 0, 1, 1)
                self.gridLayout_2.setColumnStretch(1,8)
                self.gridLayout_2.setColumnStretch(3,1)
                self.gridLayout_2.setColumnStretch(5,1)
                self.gridLayout_2.setColumnStretch(7,2)
                self.gridLayout.addWidget(self.groupBoxPecas, 2, 0, 1, 1)
                #serviços
                self.groupBoxServicos = QtWidgets.QGroupBox(self.framedados)
                self.vlayoutgservicos = QtWidgets.QVBoxLayout(self.groupBoxServicos)
                self.vlayoutgservicos.setContentsMargins(1, 1, 1, 1)
                self.scrollarea2 = QtWidgets.QScrollArea(self.groupBoxServicos)
                self.scrollarea2.setWidgetResizable(True)
                self.scrollarea2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
                self.vlayoutgservicos.addWidget(self.scrollarea2)
                self.framegroupboxservicos = QtWidgets.QFrame(self.scrollarea2)
                self.framegroupboxservicos.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
                self.scrollarea2.setWidget(self.framegroupboxservicos)
                self.gridLayout_5 = QtWidgets.QGridLayout(self.framegroupboxservicos)
                self.labelNomeServico = QtWidgets.QLabel(self.framegroupboxservicos)
                self.gridLayout_5.addWidget(self.labelNomeServico, 0, 0, 1, 1)
                self.lineEditNomeServico = QtWidgets.QLineEdit(self.framegroupboxservicos)
                self.gridLayout_5.addWidget(self.lineEditNomeServico, 0, 1, 1, 1)
                self.labelQtdeS = QtWidgets.QLabel(self.framegroupboxservicos)
                self.gridLayout_5.addWidget(self.labelQtdeS, 0, 2, 1, 1)
                self.lineEditQtdeS = QtWidgets.QLineEdit(self.framegroupboxservicos)
                self.gridLayout_5.addWidget(self.lineEditQtdeS, 0, 3, 1, 1)
                self.labelValorServico = QtWidgets.QLabel(self.framegroupboxservicos)
                self.gridLayout_5.addWidget(self.labelValorServico, 0, 4, 1, 1)
                self.lineEditValorServico = QtWidgets.QLineEdit(self.framegroupboxservicos)
                self.gridLayout_5.addWidget(self.lineEditValorServico, 0, 5, 1, 1)
                self.botaoAddServicos = QtWidgets.QPushButton(self.framegroupboxservicos, clicked=self.addLinhaServico)
                self.gridLayout_5.addWidget(self.botaoAddServicos, 0, 6, 1, 1)
                self.linhasServicos = [[self.lineEditNomeServico, self.lineEditQtdeS, self.lineEditValorServico]]
                self.spacerservico = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
                self.gridLayout_5.addItem(self.spacerservico, 1, 0, 1, 1)
                self.gridLayout_5.setColumnStretch(1,12)
                self.gridLayout_5.setColumnStretch(3,1)
                self.gridLayout_5.setColumnStretch(5,2)
                self.gridLayout.addWidget(self.groupBoxServicos, 2, 1, 1, 1)
                #valor
                self.framevalor = QtWidgets.QFrame(self.framedados)
                self.hlayoutvalor = QtWidgets.QHBoxLayout(self.framevalor)
                self.labelValorTotal1 = QtWidgets.QLabel(self.framevalor)
                self.labelValorTotal1.setText("VALOR TOTAL: R$")
                self.labelValorTotal2 = QtWidgets.QLabel(self.framevalor)
                spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
                self.hlayoutvalor.addItem(spacerItem)
                self.hlayoutvalor.addWidget(self.labelValorTotal1)
                self.hlayoutvalor.addWidget(self.labelValorTotal2)
                self.gridLayout.addWidget(self.framevalor, 3, 0, 1, -1)
                #campo de observações
                self.groupBoxObs = QtWidgets.QGroupBox(self.framedados)
                self.vlayout6_4 = QtWidgets.QVBoxLayout(self.groupBoxObs)
                self.textEdit = QtWidgets.QTextEdit(self.groupBoxObs)
                self.groupBoxObs.setMaximumHeight(120)
                self.vlayout6_4.addWidget(self.textEdit)
                self.gridLayout.addWidget(self.groupBoxObs, 4, 0, -1, -1)
                self.gridLayout.setColumnStretch(0,1)
                self.gridLayout.setColumnStretch(1,1)
                #botoes
                self.framebotoes = QtWidgets.QFrame(self.main_frame)
                self.hlayout4 = QtWidgets.QHBoxLayout(self.framebotoes)
                spacerItem5 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
                self.hlayout4.addItem(spacerItem5)
                self.botaoSalvareImprimir = QtWidgets.QPushButton(self.framebotoes)
                self.botaoSalvareImprimir.setMinimumSize(QtCore.QSize(150, 35))
                self.botaoSalvareImprimir.setObjectName('botaoprincipal')
                self.hlayout4.addWidget(self.botaoSalvareImprimir)
                self.botaoSalvar = QtWidgets.QPushButton(self.framebotoes)
                self.botaoSalvar.setMinimumSize(QtCore.QSize(100, 30))
                self.hlayout4.addWidget(self.botaoSalvar)
                self.botaolimpar = QtWidgets.QPushButton(self.framebotoes)
                self.botaolimpar.setMinimumSize(QtCore.QSize(100, 30))
                self.hlayout4.addWidget(self.botaolimpar)
                self.hlayout4.setContentsMargins(9,0,9,9)
                self.vlayout6.addWidget(self.framebotoes)
           
                self.setCentralWidget(self.main_frame)

                self.completerPeca = QtWidgets.QCompleter([])
                self.completerPeca.setCaseSensitivity(QtCore.Qt.CaseSensitivity.CaseInsensitive)
                self.completerPeca.setCompletionMode(QtWidgets.QCompleter.CompletionMode.UnfilteredPopupCompletion)
                self.lineEditNomePeca.setCompleter(self.completerPeca)
                self.completerServico = QtWidgets.QCompleter([])
                self.completerServico.setCaseSensitivity(QtCore.Qt.CaseSensitivity.CaseInsensitive)
                self.completerServico.setCompletionMode(QtWidgets.QCompleter.CompletionMode.UnfilteredPopupCompletion)
                self.lineEditNomeServico.setCompleter(self.completerServico)

                self.retranslateUi()


        def retranslateUi(self):
                _translate = QtCore.QCoreApplication.translate
                self.setWindowTitle(_translate("MainWindow", "Mecânica Pasetto"))

                self.botaoSalvareImprimir.setText(_translate("MainWindow", "Salvar e Imprimir"))
                self.botaoSalvar.setText(_translate("MainWindow", "Salvar"))
                self.botaolimpar.setText(_translate("MainWindow", "Limpar"))

                self.labelTitulo.setText(_translate("MainWindow", "Orçamentos"))
                self.groupBoxCliente.setTitle(_translate("MainWindow", "Dados do Cliente"))
                self.botaobuscarcliente.setText(_translate("MainWindow", "Selecionar Cliente"))
                self.checkboxNovoCliente.setText(_translate("MainWindow", "Novo Cliente"))
                self.labelNome.setText(_translate("MainWindow", "Nome*"))
                self.labelCEP.setText(_translate("MainWindow", "CEP"))
                self.labelPessoa.setText(_translate("MainWindow", "Pessoa"))
                self.labelcpfj.setText(_translate("MainWindow", "CPF"))
                self.labelUF.setText(_translate("MainWindow", "UF"))
                self.labelCidade.setText(_translate("MainWindow", "Cidade"))
                self.labelEnder.setText(_translate("MainWindow", "Endereço"))
                self.labelNumero.setText(_translate("MainWindow", "nº"))
                self.labelBairro.setText(_translate("MainWindow", "Bairro"))
                self.labelFone1.setText(_translate("MainWindow", "Fone 1"))
                self.labelFone2.setText(_translate("MainWindow", "Fone 2"))
                self.groupBoxVeiculo.setTitle(_translate("MainWindow", "Dados do veículo"))
                self.botaobuscarveiculo.setText(_translate("MainWindow", "Selecionar Veículo"))
                self.checkboxNovoVeiculo.setText(_translate("MainWindow", "Novo Veículo"))
                self.labelMarca.setText(_translate("MainWindow", "Marca*"))
                self.labelPlaca.setText(_translate("MainWindow", "Placa*"))
                self.labelAno.setText(_translate("MainWindow", "Ano*"))
                self.labelModelo.setText(_translate("MainWindow", "Modelo*"))
                self.labelKm.setText(_translate("MainWindow", "Km*"))
                self.groupBoxOrcamento.setTitle(_translate("MainWindow", "Dados do Orçamento"))
                self.labelData.setText(_translate("MainWindow", "Data do Orçamento"))
                self.labelDataPrev.setText(_translate("MainWindow", "Data Prevista"))
                self.groupBoxServicos.setTitle(_translate("MainWindow", "Serviços"))
                self.botaoAddServicos.setText(_translate("MainWindow", "+"))
                self.labelValorServico.setText(_translate("MainWindow", "Valor"))
                self.labelNomeServico.setText(_translate("MainWindow", "Serviço"))
                self.labelQtdeS.setText(_translate("MainWindow", "Qtde"))
                self.groupBoxObs.setTitle(_translate("MainWindow", "Observações (Max. 200 caracteres)"))
                self.groupBoxPecas.setTitle(_translate("MainWindow", "Peças"))
                self.labelQtde.setText(_translate("MainWindow", "Qtde"))
                self.labelUn.setText(_translate("MainWindow", "Un"))
                self.botaoAddPecas.setText(_translate("MainWindow", "+"))
                self.labelNomePeca.setText(_translate("MainWindow", "Peça"))
                self.labelValorPeca.setText(_translate("MainWindow", "Valor"))

        def addLinhaPeca(self):
                label1 = QtWidgets.QLabel(text="Peça")
                lineedit1 = QtWidgets.QLineEdit()
                label2 = QtWidgets.QLabel(text="Qtde")
                lineedit2 = QtWidgets.QLineEdit()
                label3 = QtWidgets.QLabel(text="Un")
                comboBox = QtWidgets.QComboBox()
                comboBox.addItems(UNIDADES)
                comboBox.setCurrentIndex(15)
                label4 = QtWidgets.QLabel(text="Valor")
                lineedit4 = QtWidgets.QLineEdit()
                self.gridLayout_2.addWidget(label1, len(self.linhasPeca), 0, 1, 1)
                self.gridLayout_2.addWidget(lineedit1, len(self.linhasPeca), 1, 1, 1)
                self.gridLayout_2.addWidget(label2, len(self.linhasPeca), 2, 1, 1)
                self.gridLayout_2.addWidget(lineedit2, len(self.linhasPeca), 3, 1, 1)
                self.gridLayout_2.addWidget(label3, len(self.linhasPeca), 4, 1, 1)
                self.gridLayout_2.addWidget(comboBox, len(self.linhasPeca), 5, 1, 1)
                self.gridLayout_2.addWidget(label4, len(self.linhasPeca), 6, 1, 1)
                self.gridLayout_2.addWidget(lineedit4, len(self.linhasPeca), 7, 1, 1)
                self.linhasPeca.append([lineedit1, lineedit2, comboBox, lineedit4])
                self.gridLayout_2.addWidget(self.botaoAddPecas, len(self.linhasPeca)-1, 8, 1, 1)
                self.gridLayout_2.removeItem(self.spacerpeca)
                self.gridLayout_2.addItem(self.spacerpeca, len(self.linhasPeca), 0, 1, 1)


        def addLinhaServico(self):
                label1 = QtWidgets.QLabel(text="Serviço")
                lineedit1 = QtWidgets.QLineEdit()
                label2 = QtWidgets.QLabel(text="Qtde")
                lineedit2 = QtWidgets.QLineEdit()
                label3 = QtWidgets.QLabel(text="Valor")
                lineedit3 = QtWidgets.QLineEdit()
                self.gridLayout_5.addWidget(label1, len(self.linhasServicos), 0, 1, 1)
                self.gridLayout_5.addWidget(lineedit1, len(self.linhasServicos), 1, 1, 1)
                self.gridLayout_5.addWidget(label2, len(self.linhasServicos), 2, 1, 1)
                self.gridLayout_5.addWidget(lineedit2, len(self.linhasServicos), 3, 1, 1)
                self.gridLayout_5.addWidget(label3, len(self.linhasServicos), 4, 1, 1)
                self.gridLayout_5.addWidget(lineedit3, len(self.linhasServicos), 5, 1, 1)
                self.linhasServicos.append([lineedit1, lineedit2, lineedit3])
                self.gridLayout_5.addWidget(self.botaoAddServicos, len(self.linhasServicos)-1, 6, 1, 1)
                self.gridLayout_5.removeItem(self.spacerservico)
                self.gridLayout_5.addItem(self.spacerservico, len(self.linhasServicos), 0, 1, 1)

        def setCliente(self, nome, cpf=None, cnpj=None, cep=None, ender=None, num=None, bairro=None, cidade=None, uf=None, tel1=None, tel2=None):
                self.lineEditNomeCliente.setText(nome)
                self.lineEditCEP.setText(cep)
                self.lineEditEnder.setText(ender)
                self.lineEditNumero.setText(num)
                self.lineEditBairro.setText(bairro)
                if cpf:
                        self.lineEditCPFJ.setText(cpf)
                        self.labelcpfj.setText("CPF")
                        self.comboBoxPessoa.setCurrentIndex(0)
                elif cnpj:
                        self.lineEditCPFJ.setText(cnpj)
                        self.labelcpfj.setText("CNPJ")
                        self.comboBoxPessoa.setCurrentIndex(1)
                self.lineEditCidade.setText(cidade)
                if uf:
                        for index in range(self.comboBoxuf.count()):
                                if(self.comboBoxuf.itemText(index)==uf):
                                        self.comboBoxuf.setCurrentIndex(index)
                                        break
                self.lineEditFone1.setText(tel1)
                self.lineEditFone2.setText(tel2)

        def setClienteReadOnly(self, flag: bool):
                if flag:
                        self.comboBoxPessoa.setDisabled(True)                        
                        self.lineEditCPFJ.setReadOnly(True)
                        self.lineEditNomeCliente.setReadOnly(True)
                        self.lineEditCEP.setReadOnly(True)
                        self.lineEditEnder.setReadOnly(True)
                        self.lineEditNumero.setReadOnly(True)
                        self.lineEditBairro.setReadOnly(True)
                        self.lineEditCidade.setReadOnly(True)
                        self.comboBoxuf.setDisabled(True)
                        self.lineEditFone1.setReadOnly(True)
                        self.lineEditFone2.setReadOnly(True)
                else:
                        self.comboBoxPessoa.setDisabled(False)                        
                        self.lineEditCPFJ.setReadOnly(False)
                        self.lineEditNomeCliente.setReadOnly(False)
                        self.lineEditCEP.setReadOnly(False)
                        self.lineEditEnder.setReadOnly(False)
                        self.lineEditNumero.setReadOnly(False)
                        self.lineEditBairro.setReadOnly(False)
                        self.lineEditCidade.setReadOnly(False)
                        self.comboBoxuf.setDisabled(False)
                        self.lineEditFone1.setReadOnly(False)
                        self.lineEditFone2.setReadOnly(False)

        def getDadosCliente(self):
                dict = {}
                if(self.lineEditCPFJ.text()):
                    if(self.comboBoxPessoa.currentIndex()==0):
                        dict['cpf'] = self.lineEditCPFJ.text()
                    else:
                        dict['cnpj'] = self.lineEditCPFJ.text()
                if(self.lineEditNomeCliente.text()):
                    dict['nome'] = self.lineEditNomeCliente.text()
                if(self.lineEditCEP.text()):
                    dict['cep'] = self.lineEditCEP.text()
                if(self.lineEditEnder.text()):
                    dict['endereco'] = self.lineEditEnder.text()
                if(self.lineEditNumero.text()):
                    dict['numero'] = self.lineEditNumero.text()
                if(self.lineEditBairro.text()):
                    dict['bairro'] = self.lineEditBairro.text()
                if(self.lineEditCidade.text()):
                    dict['cidade'] = self.lineEditCidade.text()
                dict['estado'] = self.comboBoxuf.currentText()
                return dict

        def getFones(self):
                fones = []
                if(self.lineEditFone1.text()):
                    fones.append(self.lineEditFone1.text())
                if(self.lineEditFone2.text()):
                    fones.append(self.lineEditFone2.text())
                return fones

        def setEndereco(self, cep=None, ender=None, num=None, bairro=None, cidade=None, uf=None):
                self.lineEditCEP.setText(cep)
                self.lineEditEnder.setText(ender)
                self.lineEditNumero.setText(num)
                self.lineEditBairro.setText(bairro)
                self.lineEditCidade.setText(cidade)
                if uf:
                        for index in range(self.comboBoxuf.count()):
                                if(self.comboBoxuf.itemText(index)==uf):
                                        self.comboBoxuf.setCurrentIndex(index)
                                        break


        def setVeiculo(self, marca, modelo, placa, ano=None):
                self.lineEditModelo.setText(modelo)
                self.lineEditAno.setText(ano)
                self.lineEditPlaca.setText(placa)
                for index in range(self.comboBoxMarca.count()):
                                if(self.comboBoxMarca.itemText(index)==marca):
                                        self.comboBoxMarca.setCurrentIndex(index)
                                        break

        def setVeiculoReadOnly(self, flag: bool):
                if flag:
                        self.comboBoxMarca.setDisabled(True)                        
                        self.lineEditModelo.setReadOnly(True)
                        self.lineEditAno.setReadOnly(True)
                        self.lineEditPlaca.setReadOnly(True)
                else:
                        self.comboBoxMarca.setDisabled(False)                        
                        self.lineEditModelo.setReadOnly(False)
                        self.lineEditAno.setReadOnly(False)
                        self.lineEditPlaca.setReadOnly(False)

        def getDadosVeiculo(self):
                dict = {}
                dict['marca'] = self.comboBoxMarca.currentText()
                if(self.lineEditModelo.text()):
                        dict['modelo'] = self.lineEditModelo.text()
                if(self.lineEditPlaca.text()):
                        dict['placa'] = self.lineEditPlaca.text()
                if(self.lineEditAno.text()):
                        dict['ano'] = self.lineEditAno.text()
                if(self.lineEditEnder.text()):
                        dict['endereco'] = self.lineEditEnder.text()
                return dict


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = TelaCadastroOrcamento()
    ui.setupUi()
    ui.show()
    style = open('./ui/styles.qss').read()
    app.setStyleSheet(style)
    sys.exit(app.exec())